# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: newlifebegins
email: wangwei112012232@163.com
description: >
    fullstack web developer
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://newlifebegins.github.io" # the base hostname & protocol for your site
github_username: newlifebegins
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num"
favicon: favicon.ico

# Build settings
markdown: kramdown

